SET SQLPROMPT "W21050558 > "

SET VERIFY ON

/* Setup File for DML, DMA FINAL ASSIGNMENT PART2 */

SET ECHO ON

SET SQLBLANKLINES ON

SET SERVEROUTPUT ON SIZE 30000

/* PART2, QUESTION B, SUBQUESTION Q1 */

CREATE OR REPLACE PROCEDURE PART2BQ1 AS

  vPROPERTY_ID          PROPERTY.PROPERTY_ID%TYPE;
  vOWNER_ID             PROPERTY.OWNER_ID%TYPE;
  vBRANCH_ID            PROPERTY.BRANCH_ID%TYPE;
  vSELLING_PRICE        PROPERTY.SELLING_PRICE%TYPE;
  vREGISTRATION_DATE    PROPERTY.REGISTRATION_DATE%TYPE;
  vADDRESS              PROPERTY.ADDRESS%TYPE;
  vLOCATION             PROPERTY.LOCATION%TYPE;
  vTYPE                 PROPERTY.TYPE%TYPE;
  vROOMS                PROPERTY.ROOMS%TYPE;
  vSTATUS               PROPERTY.STATUS%TYPE;

  CURSOR PROPERTY_FOR_SALE_CURSOR IS
    SELECT p.PROPERTY_ID, p.OWNER_ID, p.BRANCH_ID, p.SELLING_PRICE, p.REGISTRATION_DATE, p.ADDRESS,
           p.LOCATION, p.TYPE, p.ROOMS, p.STATUS
    FROM PROPERTY p, CUSTOMER_INTENTION ci
    WHERE p.OWNER_ID = ci.CUSTOMER_ID
    AND   ci.PURPOSE = 'SELL'
    AND   p.STATUS = 'AVAILABLE'
    AND   p.TYPE in ('DETACHED', 'SEMI DETACHED')
    AND   p.ROOMS >= 4
    AND   p.LOCATION IN ('FENHAM','HEATON')
    AND   p.REGISTRATION_DATE > SYSDATE-42
    ORDER BY REGISTRATION_DATE DESC;

BEGIN

  OPEN PROPERTY_FOR_SALE_CURSOR;

  LOOP
    FETCH PROPERTY_FOR_SALE_CURSOR INTO vPROPERTY_ID, vOWNER_ID, vBRANCH_ID, vSELLING_PRICE, vREGISTRATION_DATE,
    vADDRESS, vLOCATION, vTYPE, vROOMS, vSTATUS;
    EXIT WHEN PROPERTY_FOR_SALE_CURSOR%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE('Property ID is: ' || vPROPERTY_ID);
    DBMS_OUTPUT.PUT_LINE('Owner ID is: ' || vOWNER_ID);
    DBMS_OUTPUT.PUT_LINE('Branch ID is: ' || vBRANCH_ID);
    DBMS_OUTPUT.PUT_LINE('Selling price is: ' || vSELLING_PRICE);
    DBMS_OUTPUT.PUT_LINE('Registration date is: ' || vREGISTRATION_DATE);
    DBMS_OUTPUT.PUT_LINE('Address is: ' || vADDRESS);
    DBMS_OUTPUT.PUT_LINE('Location is: ' || vLOCATION);
    DBMS_OUTPUT.PUT_LINE('Type is: ' || vTYPE);
    DBMS_OUTPUT.PUT_LINE('Number of rooms is: ' || vROOMS);
    DBMS_OUTPUT.PUT_LINE('Status is: ' || vSTATUS);
    DBMS_OUTPUT.PUT_LINE(CHR(10));
  END LOOP;

  IF PROPERTY_FOR_SALE_CURSOR%ISOPEN THEN
    CLOSE PROPERTY_FOR_SALE_CURSOR;
  END IF;

  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('AN ERROR HAS OCCURED');
      IF PROPERTY_FOR_SALE_CURSOR%ISOPEN THEN
        CLOSE PROPERTY_FOR_SALE_CURSOR;
      END IF;
END;
/

/* PART2, QUESTION B, SUBQUESTION Q2 */

CREATE OR REPLACE PROCEDURE PART2BQ2 AS

  vBUYER_ID             PROPERTY_SOLD.BUYER_ID%TYPE;
  vPROPERTY_ID          PROPERTY_SOLD.PROPERTY_ID%TYPE;
  vSELLING_PRICE        PROPERTY_SOLD.SELLING_PRICE%TYPE;
  vSTAMP_DUTY           PROPERTY_SOLD.STAMP_DUTY%TYPE;
  vCOMMISSION           PROPERTY_SOLD.COMMISSION%TYPE;
  vTRANSACTION_DATE     PROPERTY_SOLD.TRANSACTION_DATE%TYPE;

  CURSOR PROPERTY_SOLD_CURSOR IS
    SELECT ps.BUYER_ID, ps.PROPERTY_ID, ps.SELLING_PRICE, ps.STAMP_DUTY, ps.COMMISSION, ps.TRANSACTION_DATE
    FROM PROPERTY_SOLD ps, PROPERTY p
    WHERE ps.PROPERTY_ID = p.PROPERTY_ID
    AND p.LOCATION in ('NEWCASTLE','SUNDERLAND','GATESHEAD','CRAMLINGTON')
    AND ps.SELLING_PRICE BETWEEN 195000 AND 375000
    AND TRANSACTION_DATE BETWEEN '01-JAN-2018' AND '31-DEC-2022'
    ORDER BY TRANSACTION_DATE DESC;

BEGIN

  OPEN PROPERTY_SOLD_CURSOR;

  LOOP
    FETCH PROPERTY_SOLD_CURSOR INTO vBUYER_ID, vPROPERTY_ID, vSELLING_PRICE, vSTAMP_DUTY, vCOMMISSION, vTRANSACTION_DATE;
    EXIT WHEN PROPERTY_SOLD_CURSOR%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE('Buyer ID is: ' || vBUYER_ID);
    DBMS_OUTPUT.PUT_LINE('Property ID is: ' || vPROPERTY_ID);
    DBMS_OUTPUT.PUT_LINE('Selling price of the property is: ' || vSELLING_PRICE);
    DBMS_OUTPUT.PUT_LINE('Stamp duty for the property is: ' || vSTAMP_DUTY);
    DBMS_OUTPUT.PUT_LINE('Commission for the property is: ' || vCOMMISSION);
    DBMS_OUTPUT.PUT_LINE('Date of the transaction is: ' || vTRANSACTION_DATE);
    DBMS_OUTPUT.PUT_LINE(CHR(10));
  END LOOP;

  IF PROPERTY_SOLD_CURSOR%ISOPEN THEN
    CLOSE PROPERTY_SOLD_CURSOR;
  END IF;

  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('AN ERROR HAS OCCURED');
      IF PROPERTY_SOLD_CURSOR%ISOPEN THEN
        CLOSE PROPERTY_SOLD_CURSOR;
      END IF;
END;
/
