SET VERIFY ON

Rem	Setup File for DDL, DMA FINAL ASSIGNMENT PART1

SET ECHO ON

SET SQLBLANKLINES ON

CREATE TABLE AGENT (
    AGENT_ID            NUMBER(3)  NOT NULL
      CHECK (AGENT_ID > 0)
      CONSTRAINT PK_AGENT PRIMARY KEY,
    HEADQUARTER         VARCHAR(25),
    FULL_NAME           VARCHAR(50) NOT NULL
      CONSTRAINT AGENT_UNIQUE_FN UNIQUE,
    ADDRESS             VARCHAR(100),
    WEBSITE             VARCHAR(50),
    CONTACT_DETAILS     NUMBER(14)  NOT NULL
      CONSTRAINT AGENT_UNIQUE_CD UNIQUE
  );

  CREATE TABLE BRANCH (
    BRANCH_ID           NUMBER(3)  NOT NULL
      CHECK (BRANCH_ID > 0)
      CONSTRAINT PK_BRANCH PRIMARY KEY,
    AGENT_ID            NUMBER(3)  NOT NULL
      CHECK (AGENT_ID > 0)
      CONSTRAINT FK_BRANCH REFERENCES AGENT,
    ADDRESS             VARCHAR(100),
    CONTACT_DETAILS     NUMBER(14)  NOT NULL
      CONSTRAINT BRANCH_UNIQUE_CD UNIQUE,
    MANAGER_ID          NUMBER(3)  NOT NULL
      CONSTRAINT BRANCH_UNIQUE_MNGR UNIQUE
  );

  CREATE TABLE STAFF (
    STAFF_ID            NUMBER(3) NOT NULL
      CHECK (STAFF_ID > 0)
      CONSTRAINT PK_STAFF PRIMARY KEY,
    AGENT_ID            NUMBER(3)  NOT NULL
      CHECK (AGENT_ID > 0)
      CONSTRAINT FK_BRANCH REFERENCES AGENT,
    FULL_NAME           VARCHAR(50) NOT NULL,
    ADDRESS             VARCHAR(100),
    CONTACT_DETAILS     NUMBER(14)  NOT NULL
      CONSTRAINT STAFF_UNIQUE_CD UNIQUE,
    PERSONAL_DETAILS    CHAR(1)
      CONSTRAINT STAFF_PERS_DETAILS CHECK (PERSONAL_DETAILS IN ('S', 'M', 'W', 'D'))
  );

  CREATE TABLE CUSTOMER (
    CUSTOMER_ID         NUMBER(3) NOT NULL
      CHECK (CUSTOMER_ID > 0)
      CONSTRAINT PK_CUSTOMER PRIMARY KEY,
    AGENT_ID            NUMBER(3)  NOT NULL
      CHECK (AGENT_ID > 0)
      CONSTRAINT FK_BRANCH REFERENCES AGENT,
    FULL_NAME           VARCHAR(50) NOT NULL,
    ADDRESS             VARCHAR(100),
    DOB                 DATE,
      CONSTRAINT CUST_OVER_18_YO CHECK (TO_DATE (DOB, 'DD-MON-YYYY') > '01-JAN-2004'),
    GENDER              CHAR(1)
      CONSTRAINT CUST_GENDER CHECK (GENDER IN ('M', 'F')),
    CONTACT_DETAILS     NUMBER(14)  NOT NULL
      CONSTRAINT CUST_UNIQUE_CD UNIQUE
  );

  CREATE TABLE CUSTOMER_INTENTION (
    CUSTOMER_ID         NUMBER(3) NOT NULL
      CHECK (CUSTOMER_ID > 0)
      CONSTRAINT PK_CUSTOMER PRIMARY KEY,
      CONSTRAINT FK_CUST_INTENT REFERENCES CUSTOMER,
    PURPOSE             CHAR(1) NOT NULL
      CONSTRAINT PURPOSE_CHK CHECK (PURPOSE IN ('BUY', 'RENT', 'SELL'))
  );

  CREATE TABLE PROPERTY (
    PROPERTY_ID         NUMBER(3) NOT NULL
      CHECK (PROPERTY_ID > 0)
      CONSTRAINT PK_PROPERTY PRIMARY KEY,
    CUSTOMER_ID         NUMBER(3) NOT NULL
      CHECK (CUSTOMER_ID > 0)
      CONSTRAINT FK1_PROP REFERENCES CUSTOMER,
    BRANCH_ID           NUMBER(3)  NOT NULL
      CHECK (BRANCH_ID > 0)
      CONSTRAINT FK2_PROP REFERENCES BRANCH,
    REGISTRATION_DATE   DATE,
    ADDRESS             VARCHAR(100),
    LOCATION            (25),
    DESCRIPTION         VARCHAR(300),
    ACCOM_DETAILS       VARCHAR(300),
    TYPE                CHAR(2)
      CONSTRAINT TYPE_CHK CHECK (TYPE IN ('D', 'SD')),
    ROOMS               NUMBER(2)
      CHECK (ROOMS > 0)
  );

  CREATE TABLE PROPERTY_SOLD (
    BUYER_ID            NUMBER(3) NOT NULL
      CHECK (BUYER_ID > 0)
      CONSTRAINT PK_PROP_SOLD PRIMARY KEY
      CONSTRAINT FK1_PROP_SOLD REFERENCES CUSTOMER,
    PROPERTY_ID         NUMBER(3) NOT NULL
      CHECK (PROPERTY_ID > 0)
      CONSTRAINT FK2_PROP_SOLD REFERENCES CUSTOMER,
    SELLING_PRICE       NUMBER(9,2) NOT NULL
      CONSTRAINT SP_POS CHECK (SELLING_PRICE > 0),
    STAMP_DUTY          NUMBER(6,2)
      CONSTRAINT SD_POS CHECK (STAMP_DUTY > 0),
    COMMISSION          NUMBER(6,2)
      CONSTRAINT COMM_POS CHECK (COMMISSION > 0)
  );

  CREATE TABLE PROPERTY_RENTED (
    TENANT_ID            NUMBER(3) NOT NULL
      CHECK (TENANT_ID > 0)
      CONSTRAINT PK_PROP_RENT PRIMARY KEY
      CONSTRAINT FK1_PROP_RENT REFERENCES CUSTOMER,
    PROPERTY_ID         NUMBER(3) NOT NULL
      CHECK (PROPERTY_ID > 0)
      CONSTRAINT FK2_PROP_RENT REFERENCES CUSTOMER,
    LANDLORD_ID         NUMBER(3) NOT NULL
      CHECK (TENANT_ID > 0),
      CONSTRAINT FK3_PROP_RENT REFERENCES CUSTOMER,
    RENT_PER_MONTH      NUMBER(6,2) NOT NULL
      CHECK (RENT_PER_MONTH > 0),
    DEPOSIT             NUMBER(7,2)
      CHECK (DEPOSIT > 0),
    COMMISSION          NUMBER(7,2)
      CHECK (COMMISSION > 0),
    START_DATE          DATE,
    END_DATE            DATE,
      CONSTRAINT DURATION CHECK (TO_DATE (START_DATE, 'DD-MON-YYYY') <
                               TO_DATE (END_DATE, 'DD-MON-YYYY'))
    SCHEME              VARCHAR(50)
  );

  CREATE TABLE VIEWINGS (
    PROPERTY_ID         NUMBER(3) NOT NULL
      CHECK (PROPERTY_ID > 0)
      CONSTRAINT PK1_VIEW PRIMARY KEY
      CONSTRAINT FK1_VIEW REFERENCES CUSTOMER,
    CUSTOMER_ID         NUMBER(3) NOT NULL
      CHECK (CUSTOMER_ID > 0)
      CONSTRAINT FK2_VIEW REFERENCES CUSTOMER,
    DATE_TIME           TIMESTAMP
      CONSTRAINT PK2_VIEW PRIMARY KEY,
      CONSTRAINT WORKING_HOURS CHECK (TO_DATE(DATE_TIME, 'DD-MON-YYYY HH24:MI:SS.FF') >= '% 09:00:00.00'
                                      AND TO_DATE(DATE_TIME, 'DD-MON-YYYY HH24:MI:SS.FF') <= '% 17:30:00.00'),
    CUST_COMMENTS       VARCHAR(500)
  );
