SET VERIFY ON

Rem	Setup File for DML, DMA FINAL ASSIGNMENT PART2

SET ECHO ON

SET SQLBLANKLINES ON

Rem PART2, QUESTION B, SUBQUESTION Q1

SELECT p.*
FROM PROPERTY p, CUSTOMER_INTENTION ci
WHERE p.CUSTOMER_ID = ci.CUSTOMER_ID
AND   ci.PURPOSE = 'SELL'
AND   p.TYPE in ('DETACHED', 'SEMI DETACHED')
AND   p.ROOMS >= 4
AND   p.LOCATION = 'NEWCASTLE'
AND   p.ADDRESS IN ('%, HEATON', '%, FENHAM')
AND   p.REGISTRATION_DATE > SYSDATE-42

Rem PART2, QUESTION B, SUBQUESTION Q2


SELECT ps.*
FROM PROPERTY_SOLD ps, PROPERTY p
WHERE ps.PROPERTY_ID = p.PROPERTY_ID
AND p.LOCATION in ('NEWCASTLE','SUNDERLAND','GATESHEAD','CRAMLINGTON')
AND ps.SELLING_PRICE BETWEEN 195000 AND 375000
AND TRANSACTION_DATE BETWEEN '%2018' AND '%2022'
ORDER BY TRANSACTION_DATE DESC

DECLARE
  vBUYER_ID             PROPERTY_SOLD.BUYER_ID%TYPE;
  vPROPERTY_ID          PROPERTY_SOLD.PROPERTY_ID%TYPE;
  vADDRESS              PROPERTY.ADDRESS%TYPE;
  vLOCATION             PROPERTY.LOCATION%TYPE;
  vDESCRIPTION          PROPERTY.DESCRIPTION%TYPE;
  vACCOM_DETAILS        PROPERTY.ACCOM_DETAILS%TYPE;
  vTYPE                 PROPERTY.TYPE%TYPE;
  vROOMS                PROPERTY.ROOMS%TYPE;
  vSELLING_PRICE        PROPERTY_SOLD.SELLING_PRICE%TYPE;
  vSTAMP_DUTY           PROPERTY_SOLD.STAMP_DUTY%TYPE;
  vCOMMISSION           PROPERTY_SOLD.COMMISSION%TYPE;
  vTRANSACTION_DATE     PROPERTY_SOLD.TRANSACTION_DATE%TYPE;

  CURSOR PROPERTY_SOLD_CURSOR IS
    SELECT ps.BUYER_ID, ps.PROPERTY_ID, p.ADDRESS, p.LOCATION, p.DESCRIPTION, p.ACCOM_DETAILS, p.TYPE, p.ROOMS,
            ps.SELLING_PRICE, ps.STAMP_DUTY, ps.COMMISSION, ps.TRANSACTION_DATE
    FROM PROPERTY_SOLD ps, PROPERTY p
    WHERE ps.PROPERTY_ID = p.PROPERTY_ID
    AND p.LOCATION in ('NEWCASTLE','SUNDERLAND','GATESHEAD','CRAMLINGTON')
    AND ps.SELLING_PRICE BETWEEN 195000 AND 375000
    AND TRANSACTION_DATE BETWEEN '%2018' AND '%2022'
    ORDER BY TRANSACTION_DATE DESC

BEGIN

  OPEN PROPERTY_SOLD_CURSOR;

  LOOP
    FETCH PROPERTY_SOLD_CURSOR
      vBUYER_ID, vPROPERTY_ID, vSELLING_PRICE, vSTAMP_DUTY, vCOMMISSION, vTRANSACTION_DATE;
    EXIT WHEN PROPERTY_SOLD_CURSOR%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE('Buyer ID is: ' || vBUYER_ID);
    DBMS_OUTPUT.PUT_LINE('Property ID is: ' || vPROPERTY_ID);
    DBMS_OUTPUT.PUT_LINE('Property address is: ' || vADDRESS);
    DBMS_OUTPUT.PUT_LINE('property location is: ' || vLOCATION);
    IF p.DESCRIPTION IS NOT NULL THEN
      DBMS_OUTPUT.PUT_LINE('Property description is: ' || vDESCRIPTION);
    ELSE
      DBMS_OUTPUT.PUT_LINE('Property description is: NULL');
    END IF;
    DBMS_OUTPUT.PUT_LINE('Accommodation details are: ' || vACCOM_DETAILS);
    DBMS_OUTPUT.PUT_LINE('Property type is: ' || vTYPE);
    DBMS_OUTPUT.PUT_LINE('Number of rooms in the property: ' || vROOMS);
    DBMS_OUTPUT.PUT_LINE('Selling price of the property is: ' || vSELLING_PRICE);
    DBMS_OUTPUT.PUT_LINE('Stamp duty for the property is: ' || vSTAMP_DUTY);
    DBMS_OUTPUT.PUT_LINE('Commission for the property is ' || vCOMMISSION);
    DBMS_OUTPUT.PUT_LINE('Date of the transaction is: ' || vTRANSACTION_DATE);
  END LOOP;

  IF PROPERTY_SOLD_CURSOR%ISOPEN THEN CLOSE PROPERTY_SOLD_CURSOR END IF;

  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('AN ERROR HAS OCCURED');
      IF PROPERTY_SOLD_CURSOR%ISOPEN THEN CLOSE PROPERTY_SOLD_CURSOR END IF;
END;
